### ISSUE TITLE
Implement MPC controller

### ISSUE THREAD

**Issue by jruths** [Nova-UTD/meta#14]
The steering controller takes in a reference trajectory of the path we want the vehicle to take and turns that into a sequence of steering angles (and eventually velocities, but we're not doing speed cruise control in this demo).  These steering angles will go to the steering interface to literally turn the wheel.  The approach here will likely use a bit of control theory (think a fancy version of how you might have programmed that little robot to follow a piece of tape on the ground) to smooth out the response of the vehicle.

**Comment by wheitman** [comment]
For reference, Autoware provides two controllers at the moment, MPC and Pure Pursuit. I believe MPC is the newer and generally better one.

- [MPC](https://autowarefoundation.gitlab.io/autoware.auto/AutowareAuto/mpc-controller-design.html)
   - [node source](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/tree/master/src/control/mpc_controller_nodes)
- [Pure pursuit](https://autowarefoundation.gitlab.io/autoware.auto/AutowareAuto/pure-pursuit.html)
   - [node source](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/tree/master/src/control/pure_pursuit_nodes)
