### ISSUE TITLE
Lanelet2 map annotation

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/meta#3]
In order for the route publisher, path planner, and other key planning features to work, we'll need to provide an annotated/"semantic" map for reference. Autoware uses a format called [Lanelet2](https://github.com/fzi-forschungszentrum-informatik/Lanelet2#documentation) to represent lanes, traffic signals, speed limits, and other road features in a digital format.

We'll need to:
1. Create a minimal OpenStreetMap map file (.osm). The Lanelet2 library can easily convert these into their format.
     - Take a look at the [JOSM editor](https://wiki.openstreetmap.org/wiki/JOSM)
     - [Here's our test route](https://www.google.com/maps/d/edit?mid=1AHIgeZ7EKiN8XM6JMKLwg3TFj4UUhovu&usp=sharing)
     - "Minimal" means that we just need the [lanelets](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/doc/LaneletPrimitives.md#lanelet) along the route. Per their documentation (below), each lanelet only needs a `participants` and `speed limit` property.
2. Use [existing Autoware code](https://autowarefoundation.gitlab.io/autoware.auto/AutowareAuto/lanelet2-map-for-autoware-auto.html) to broadcast our map file to the nodes that require it.

Once we have a solid .osm file, we can use it for a long time. So this only needs to be done once.

**Comment by saaketporay** [comment]
look through this and the other articles on our wiki, and work through the ROS crash course. Based on the unassigned Issues, looks like we'll need you to spearhead the Lanelet2 map creation. So you'll want to get familiarized with the Lanelet2 documentation, specifically this article.

**Comment by saaketporay** [comment]
Just comment for myself ^^

**Comment by wheitman** [comment]
Many simulator maps that SVL provides have matching .osm files already, so we can use them for testing if necessary. [See here](https://content.lgsvlsimulator.com/maps), and click a map to see the Lanelet2 link for each.
