### ISSUE TITLE
Design battery management interface

### ISSUE THREAD

**Issue by wheitman** [Nova-UTD/meta#8]
This should have two parts: 
- a physical device to link the batteries to the CAN network or Jetson directly
- a ROS node to publish the battery data

The available metrics are self-explanatory: estimated capacity, voltage, estimated remaining mileage, and maybe even a record of battery capacity over time with a projection [(like this on Android phones)](https://images.idgesg.net/images/article/2018/09/android-9-pie-battery-stats-100771684-large.jpg)

We could use this node to implement some safety features, like
- Forced low-power mode, which could disable autonomous driving
- Restricting destination options to the operating range

**Comment by crsz20** [comment]
Here are some possibly useful starting points:

- Look into the car's Battery Management Controller (BMC). It is already connected to the CAN bus, so perhaps it'll provide some useful data
- Inspect the battery for any remaining ports. Perhaps we could use a device such as Battery Management Systems (BMS) that monitor the battery (ex: [Cerbo GX](https://www.victronenergy.com/panel-systems-remote-monitoring/cerbo-gx#pd-nav-secondimage) is found in various forums)

**Comment by saaketporay** [comment]
I think I might have an idea on what to do once I get back to campus
